### PR TITLE
fix #63

### LINKED ISSUE #63: Set retry in configuration
Make it configurable for retries in configuration.

For e.g.

in worker.conf
```
[global]
retry = 3

[[mirrors]]
retry = 0
```

### PR DESCRIPTION
**Pull request by kinosang**

### CODE REVIEW

**Comment by bigeagle** [comment]
Thanks a lot! But unit tests seems to be failed.

**Comment by kinosang** [comment]
Yes, I'm trying to fix it

**Comment by kinosang** [comment]
@bigeagle How can I build a testing environment locally? I found that the upstream of testing environment, `mirrors.tuna.moe` is not accessible outside the Travis testing environment.

**Comment by bigeagle** [comment]
Basically you should be able to run unit tests simply by running `goconvey`.
Some permission-related preparation works might to be done. Refer https://github.com/tuna/tunasync/blob/master/.travis.yml

**Comment by kinosang** [comment]
These code now pass the test on my computer without any change, can you re-run the travis-ci to test it?

**Comment by bigeagle** [comment]
nope, still failed. Check the details https://travis-ci.org/tuna/tunasync/builds/215387469?utm_source=github_status&utm_medium=notification

**Comment by z4yx** [comment]
The test fails because Retry configuration may not be passed to newXxxxProvider(). We can check Retry and assign default value if it's zero.

Would you please cherry-pick commit 9f91d90f, so I can merge this pr.

**Pull request merged**
